# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"4\n\x0eListProductReq\x12\x15\n\x08isActive\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x0b\n\t_isActive\"<\n\x07Product\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08isActive\x18\x03 \x01(\x08\"2\n\x0fListProductResp\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.product.Product2T\n\x0eProductService\x12\x42\n\x0bListProduct\x12\x17.product.ListProductReq\x1a\x18.product.ListProductResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTPRODUCTREQ']._serialized_start=26
  _globals['_LISTPRODUCTREQ']._serialized_end=78
  _globals['_PRODUCT']._serialized_start=80
  _globals['_PRODUCT']._serialized_end=140
  _globals['_LISTPRODUCTRESP']._serialized_start=142
  _globals['_LISTPRODUCTRESP']._serialized_end=192
  _globals['_PRODUCTSERVICE']._serialized_start=194
  _globals['_PRODUCTSERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
